#!/bin/bash
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import -n URL -f test/e2e/exports/all/forgeopsAllResourceTypes.resourcetype.authz.json  
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import --type-name URL --file test/e2e/exports/all/forgeopsAllResourceTypes.resourcetype.authz.json --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import -n URL -f forgeopsAllResourceTypes.resourcetype.authz.json -D test/e2e/exports/all
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import -i 76656a38-5f8e-401b-83aa-4ccb74ce88d2 -f test/e2e/exports/all/forgeopsAllResourceTypes.resourcetype.authz.json 
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import --type-id 76656a38-5f8e-401b-83aa-4ccb74ce88d2 --file test/e2e/exports/all/forgeopsAllResourceTypes.resourcetype.authz.json --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import -i 76656a38-5f8e-401b-83aa-4ccb74ce88d2 -f forgeopsAllResourceTypes.resourcetype.authz.json -D test/e2e/exports/all 
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import -f test/e2e/exports/all/forgeopsAllResourceTypes.resourcetype.authz.json 
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import --file test/e2e/exports/all/forgeopsAllResourceTypes.resourcetype.authz.json --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import -f forgeopsAllResourceTypes.resourcetype.authz.json -D test/e2e/exports/all 
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import -af test/e2e/exports/all/forgeopsAllResourceTypes.resourcetype.authz.json 
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import --all --file test/e2e/exports/all/forgeopsAllResourceTypes.resourcetype.authz.json --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import -af forgeopsAllResourceTypes.resourcetype.authz.json -D test/e2e/exports/all 
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import -AD test/e2e/exports/all-separate/forgeops/realm/root-alpha/resourcetype 
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz type import --all-separate --directory test/e2e/exports/all-separate/forgeops/realm/root-alpha/resourcetype --force-push

# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import -i 'test-policy-set' -f test/e2e/exports/all/forgeopsAllPolicySets.policyset.authz.json --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import --set-id 'test-policy-set' --file test/e2e/exports/all/forgeopsAllPolicySets.policyset.authz.json --no-deps --prereqs
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import -i 'test-policy-set' -f forgeopsAllPolicySets.policyset.authz.json -D test/e2e/exports/all
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import -f test/e2e/exports/all/forgeopsAllPolicySets.policyset.authz.json --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import --file test/e2e/exports/all/forgeopsAllPolicySets.policyset.authz.json --no-deps --prereqs
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import -f forgeopsAllPolicySets.policyset.authz.json -D test/e2e/exports/all
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import -af test/e2e/exports/all/forgeopsAllPolicySets.policyset.authz.json --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import --all --file test/e2e/exports/all/forgeopsAllPolicySets.policyset.authz.json --no-deps --prereqs
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import -af forgeopsAllPolicySets.policyset.authz.json -D test/e2e/exports/all
FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import -AD test/e2e/exports/forgeops-authz-prereqs/policy-set-prereqs --force-push
FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz set import --all-separate --no-deps --prereqs --directory test/e2e/exports/forgeops-authz-prereqs/policy-set-prereqs


# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import -i 'Test Policy 1' -f test/e2e/exports/all/forgeopsAllPolicies.policy.authz.json --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import --policy-id 'Test Policy 1' --file test/e2e/exports/all/forgeopsAllPolicies.policy.authz.json --set-id test-policy-set --no-deps --prereqs
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import -i 'Test Policy 1' -f forgeopsAllPolicies.policy.authz.json -D test/e2e/exports/all
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import -f test/e2e/exports/all/forgeopsAllPolicies.policy.authz.json
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import --file test/e2e/exports/all/forgeopsAllPolicies.policy.authz.json --set-id test-policy-set --no-deps --prereqs --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import -f forgeopsAllPolicies.policy.authz.json -D test/e2e/exports/all
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import -af test/e2e/exports/all/forgeopsAllPolicies.policy.authz.json
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import --all --file test/e2e/exports/all/forgeopsAllPolicies.policy.authz.json --set-id test-policy-set --no-deps --prereqs --force-push
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import -af forgeopsAllPolicies.policy.authz.json -D test/e2e/exports/all
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import -AD test/e2e/exports/forgeops-authz-prereqs/policy-prereqs
# FRODO_MOCK_HOSTS=https://platform.dev.trivir.com FRODO_MOCK=record FRODO_NO_CACHE=1 FRODO_HOST=https://platform.dev.trivir.com/am frodo authz policy import --all-separate --set-id test-policy-set --no-deps --prereqs --directory test/e2e/exports/forgeops-authz-prereqs/policy-prereqs --force-push
